<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration">

        <!--api module-->
        <div style="width: 100%">
            <div class="left">
                <el-button class="el-icon-plus" @click="addDir()">新增目录</el-button>
                <el-button class="el-icon-plus" @click="addApi()">新增接口</el-button>
                <el-button class="el-icon-refresh" @click="getData()">刷新</el-button>
                <el-tree :data="apiList" :props="defaultProps" @node-click="handleNodeClick">
                    <span class="custom-tree-node" slot-scope="{ node, data }">
                        <span>{{ node.label }}</span>
                        <span>
                          <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-plus" @click="() => addDir(data)">子目录</el-button>
                          <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-plus" @click="() => addApi(data, node)">接口</el-button>
                          <el-button v-if="isApi(data) || !data.children || data.children.length <= 0 " type="text" size="mini" @click="() => delApiOrDir(data, node)">删除</el-button>
                        </span>
                      </span>
                </el-tree>
            </div>
            <div class="right">
                <!--base info-->
                <div style="width: 70%;">
                    <el-form label-width="100px"  :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">
                        <el-row>
                            <el-col :span="24">
                                <el-form-item label="name" prop="name">
                                    <span slot="label">
                                        <span>name</span>
                                    </span>
                                    <el-input v-model="saveForm.name" placeholder="name" ></el-input>
                                </el-form-item>
                            </el-col>
                        </el-row>

                        <el-row>
                            <el-col :span="24">
                                <el-form-item label="address" prop="address">
                                    <span slot="label">
                                        <span>address</span>
                                    </span>
                                    <el-input v-model="saveForm.address" placeholder="address" ></el-input>
                                </el-form-item>
                            </el-col>
                        </el-row>

                        <el-row>
                            <el-col :span="8">
                                <el-form-item label="apiVersion" prop="apiVersion">
                                    <span slot="label">
                                        <span>version</span>
                                    </span>
                                    <el-input v-model="saveForm.apiVersion" placeholder="version" ></el-input>
                                </el-form-item>
                            </el-col>

                            <el-col :span="8">
                                <el-form-item label="protocolType" prop="protocolType">
                            <span slot="label">
                                <span>protocol</span>
                                <el-tooltip class="item" effect="dark" content="protocol" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                                    <el-select v-model="saveForm.protocolType" placeholder="Please Select Protocol" style="width:100%" :filterable="true">
                                        <el-option label="http" value="1"></el-option>
                                        <el-option label="tcp" value="2"></el-option>
                                    </el-select>
                                </el-form-item>
                            </el-col>
                            <el-col :span="8">
                                <el-form-item label="type" prop="type">
                            <span slot="label">
                                <span>type</span>
                                <el-tooltip class="item" effect="dark" content="type" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                                    <el-select v-model="messageStructKey" placeholder="Please Select Type" style="width:100%" :filterable="true">
                                        <el-option label="GET" value="GET"></el-option>
                                        <el-option label="POST" value="POST"></el-option>
                                        <el-option label="HEAD" value="HEAD"></el-option>
                                        <el-option label="PUT" value="PUT"></el-option>
                                        <el-option label="PATCH" value="PATCH"></el-option>
                                        <el-option label="DELETE" value="DELETE"></el-option>
                                        <el-option label="TRACE" value="TRACE"></el-option>
                                        <el-option label="OPTIONS" value="OPTIONS"></el-option>
                                    </el-select>
                                </el-form-item>
                            </el-col>
                        </el-row>

                        <el-row>
                            <el-col :span="24">
                                <el-form-item label="remark" prop="remark">
                                    <span slot="label">
                                        <span>remark</span>
                                    </span>
                                    <el-input type="textarea" :rows="2" v-model="saveForm.remark" placeholder="remark" ></el-input>
                                </el-form-item>
                            </el-col>
                        </el-row>
                    </el-form>
                </div>
                <div style="position: absolute;right: 30px;top: 30px">
                    <el-button>保存</el-button>
                    <el-button>取消</el-button>
                </div>

                <!-- 请求参数 等。。。 -->
                <div>
                    <!--<drag-tree-table border :data="messageStructObj.parameters" rowKey="name" :columns="columns"
                                     :option_btns_width="300"
                                     :option_btns="option_btns">
                    </drag-tree-table>-->

                    <dragTreeTable
                            :data="treeData"
                            :onDrag="onTreeDataChange"
                            fixed
                            border>
                    </dragTreeTable>
                </div>

            </div>
        </div>

        <!--================================save dialog================================-->
        <el-dialog :close-on-click-modal="false" :title="dialogTitle" :visible.sync="dialogVisible"  v-loading='dialogLoading'>
            <el-form label-width="100px" :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="name" prop="name">
                            <span slot="label">
                                <span>name</span>
                            </span>
                            <el-input v-model="saveForm.name" placeholder="name" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="address" prop="address">
                            <span slot="label">
                                <span>address</span>
                            </span>
                            <el-input v-model="saveForm.address" placeholder="address" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="11">
                        <el-form-item label="apiVersion" prop="apiVersion">
                            <span slot="label">
                                <span>version</span>
                            </span>
                            <el-input v-model="saveForm.apiVersion" placeholder="version" ></el-input>
                        </el-form-item>
                    </el-col>

                    <el-col :span="11">
                        <el-form-item label="protocolType" prop="protocolType">
                            <span slot="label">
                                <span>http,tcp</span>
                                <el-tooltip class="item" effect="dark" content="http,tcp" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                            <el-select v-model="saveForm.protocolType" placeholder="Please Select Protocol" style="width:100%" :filterable="true">
                                <el-option label="http" value="1"></el-option>
                                <el-option label="tcp" value="2"></el-option>
                            </el-select>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="remark" prop="remark">
                            <span slot="label">
                                <span>remark</span>
                            </span>
                            <el-input v-model="saveForm.remark" placeholder="remark" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="saveData()" :loading="dialogLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="dialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>


    </section>
</template>
<script>
    import EnterpriseApi from './EnterpriseApi.js'

    export default EnterpriseApi
</script>
<style scoped>
    .left {
        float: left;
        width: 29%;
        height: calc(100vh - 88px);
        overflow: auto;
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
        padding: 10px;
    }
    .right {
        margin-left: 30%;
        height: calc(100vh - 88px);
        overflow-scrolling: auto;
        overflow: auto;
        position: relative;
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
        padding: 10px;
    }

    .custom-tree-node {
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: space-between;
        font-size: 14px;
        padding-right: 8px;
    }

</style>

