<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration">

        <!--api module-->
        <div style="width: 100%">
            <div class="left">
                <el-row>
                    <el-col :span="17">
                        <el-button type="primary" @click="addDir()">新增模块</el-button>
                        <el-button type="primary"  @click="reloadApiTree()" style="margin-left: 0">刷新</el-button>
<!--                        <el-button @click="openImportApiDialog()" style="margin-left: 0">导入</el-button>-->
                      <el-dropdown @command="handleCommand">
                        <el-button type="primary">
                          更多<i class="el-icon-arrow-down el-icon--right"></i>
                        </el-button>
                        <el-dropdown-menu slot="dropdown">
                          <el-dropdown-item command="import">导入</el-dropdown-item>
                          <el-dropdown-item command="export">导出</el-dropdown-item>
                        </el-dropdown-menu>
                      </el-dropdown>


                    </el-col>
                    <el-col :span="6">
                        <el-select v-model="versionId" placeholder="Version" style="width:100%" :filterable="true" @change="reloadApiTree()">
                            <el-option
                                    v-for="item in versions"
                                    :key="item.id"
                                    :label="item.version"
                                    :value="item.id">
                            </el-option>
                        </el-select>
                    </el-col>
                    <el-col :span="1">
                        <i class="el-icon-setting" style="line-height: 28px;font-size: 16px;cursor: pointer" @click="versionDialog = true"></i>
                    </el-col>
                </el-row>

                <el-tree ref="apiTree" node-key="key" :props="defaultProps" :load="loadModule" lazy @node-click="handleNodeClick">
                    <span class="custom-tree-node" slot-scope="{ data, node  }">
                        <span>{{ node.label }}</span>
                        <span>
                          <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-plus" @click="() => addDir(data, node)">子模块</el-button>
                          <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-plus" @click="() => addApi(data, node)">接口</el-button>
                          <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-refresh" @click="() => refreshByNode(node)"></el-button>
                          <el-button v-if="isApi(data) || !data.children || data.children.length <= 0 " class="el-icon-delete" type="text" size="mini" @click="() => delApiOrDir(data, node)"></el-button>
                        </span>
                      </span>
                </el-tree>
            </div>
            <div class="right" v-loading="loading">
                <!--base info-->
                <div style="width: 70%;">
                    <el-form label-width="100px"  :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">
                        <el-row>
                            <el-col :span="16">
                                <el-form-item label="name" prop="name">
                                    <span slot="label">
                                        <span>name</span>
                                    </span>
                                    <el-input v-model="saveForm.name" placeholder="name" ></el-input>
                                </el-form-item>
                            </el-col>
                            <el-col :span="8">
                                <el-form-item label="method" prop="method">
                            <span slot="label">
                                <span>method</span>
                                <el-tooltip class="item" effect="dark" content="type" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                                    <el-select v-model="saveForm.method" placeholder="Please Select Type" style="width:100%" :filterable="true">
                                        <el-option label="GET" value="GET"></el-option>
                                        <el-option label="POST" value="POST"></el-option>
                                        <el-option label="HEAD" value="HEAD"></el-option>
                                        <el-option label="PUT" value="PUT"></el-option>
                                        <el-option label="PATCH" value="PATCH"></el-option>
                                        <el-option label="DELETE" value="DELETE"></el-option>
                                        <el-option label="TRACE" value="TRACE"></el-option>
                                        <el-option label="OPTIONS" value="OPTIONS"></el-option>
                                    </el-select>
                                </el-form-item>
                            </el-col>
                        </el-row>

                        <el-row>
                            <el-col :span="24">
                                <el-form-item label="url" prop="url">
                                    <span slot="label">
                                        <span>url</span>
                                    </span>
                                    <el-input v-model="saveForm.url" placeholder="url" ></el-input>
                                </el-form-item>
                            </el-col>
                        </el-row>

                        <el-row>
                            <el-col :span="24">
                                <el-form-item label="description" prop="description">
                                    <span slot="label">
                                        <span>description</span>
                                    </span>
                                    <el-input type="textarea" :rows="2" v-model="saveForm.description" placeholder="description" ></el-input>
                                </el-form-item>
                            </el-col>
                        </el-row>
                    </el-form>
                </div>
                <div style="position: absolute;right: 30px;top: 30px">
                    <el-button @click="saveData()">保存</el-button>
                    <el-button @click="handleNodeClick({id: saveForm.id,moduleId: saveForm.moduleId})">取消</el-button>
                </div>

                <!-- 请求参数 等。。。 -->
                <div>
                    <!--<drag-tree-table border :data="messageStructObj.parameters" rowKey="name" :columns="columns"
                                     :option_btns_width="300"
                                     :option_btns="option_btns">
                    </drag-tree-table>-->
                    <span style="font-size: 16px;font-weight: bold">请求参数</span>
                    <dragTreeTable
                            :data="treeData"
                            :onDrag="onTreeDataChange"
                            fixed
                            border>
                    </dragTreeTable>

                  <span style="font-size: 16px;font-weight: bold">返回参数</span>
                  <dragTreeTable
                      :data="treeData2"
                      :onDrag="onTreeDataChange2"
                      fixed
                      border>
                  </dragTreeTable>
                </div>

            </div>
        </div>

        <!--================================save dialog================================-->
        <el-dialog :close-on-click-modal="false" :title="dialogTitle" :visible.sync="dialogVisible"  v-loading='dialogLoading'>
            <el-form label-width="100px" :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="name" prop="name">
                            <span slot="label">
                                <span>name</span>
                            </span>
                            <el-input v-model="saveForm.name" placeholder="name" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="address" prop="address">
                            <span slot="label">
                                <span>address</span>
                            </span>
                            <el-input v-model="saveForm.address" placeholder="address" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="11">
                        <el-form-item label="apiVersion" prop="apiVersion">
                            <span slot="label">
                                <span>version</span>
                            </span>
                            <el-input v-model="saveForm.apiVersion" placeholder="version" ></el-input>
                        </el-form-item>
                    </el-col>

                    <el-col :span="11">
                        <el-form-item label="protocolType" prop="protocolType">
                            <span slot="label">
                                <span>http,tcp</span>
                                <el-tooltip class="item" effect="dark" content="http,tcp" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                            <el-select v-model="saveForm.protocolType" placeholder="Please Select Protocol" style="width:100%" :filterable="true">
                                <el-option label="http" value="1"></el-option>
                                <el-option label="tcp" value="2"></el-option>
                            </el-select>
                        </el-form-item>
                    </el-col>
                </el-row>

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="remark" prop="remark">
                            <span slot="label">
                                <span>remark</span>
                            </span>
                            <el-input v-model="saveForm.remark" placeholder="remark" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="saveData()" :loading="dialogLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="dialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>

      <el-dialog :close-on-click-modal="false" title="导入" :visible.sync="importApiDialogVisible" >
        <el-form label-width="100px" :model="importApiSaveForm" ref="importApiSaveForm" :rules="rules">

          <el-row>
            <el-col :span="24">
              <el-form-item label="kind" prop="kind">
                            <span slot="label">
                                <span>文档类型</span>
                            </span>
                <el-select v-model="importApiSaveForm.kind" placeholder="Please Select Kind" style="width:100%" :filterable="true">
                  <el-option
                      v-for="item in converterProviderKinds"
                      :key="item"
                      :label="item"
                      :value="item">
                  </el-option>
                </el-select>
              </el-form-item>

              <el-form-item label="kind" prop="kind">
                            <span slot="label">
                                <span>数据格式</span>
                            </span>
                <el-select v-model="importApiSaveForm.dataFormat" placeholder="Please Select DataFormat" style="width:100%" :filterable="true">
                  <el-option label="JSON" value="JSON"></el-option>
                  <el-option label="YAML" value="YAML"></el-option>
                  <el-option label="XML" value="XML" disabled></el-option>
                </el-select>
              </el-form-item>
            </el-col>
          </el-row>

          <el-row>
            <el-col :span="24">
              <el-form-item label="content" prop="json">
                            <span slot="label">
                                <span>内容</span>
                            </span>
                <el-input type="textarea" v-model="importApiSaveForm.json" placeholder="content" ></el-input>
              </el-form-item>
            </el-col>
          </el-row>
        </el-form>
        <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="importApi()" :loading="importLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="importApiDialogVisible = false;importLoading = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
      </el-dialog>

      <el-dialog :close-on-click-modal="false" title="导入" :visible.sync="exportApiDialogVisible" >
        <el-form label-width="100px" :model="exportApiSaveForm" ref="exportApiSaveForm" :rules="rules">

          <el-row>
            <el-col :span="24">
              <el-form-item label="kind" prop="kind">
                            <span slot="label">
                                <span>文档类型</span>
                            </span>
                <el-select v-model="exportApiSaveForm.kind" placeholder="Please Select Kind" style="width:100%" :filterable="true">
                  <el-option
                      v-for="item in converterProviderKinds"
                      :key="item"
                      :label="item"
                      :value="item">
                  </el-option>
                </el-select>
              </el-form-item>

              <el-form-item label="kind" prop="kind">
                            <span slot="label">
                                <span>数据格式</span>
                            </span>
                <el-select v-model="exportApiSaveForm.dataFormat" placeholder="Please Select DataFormat" style="width:100%" :filterable="true">
                  <el-option label="JSON" value="JSON"></el-option>
                  <el-option label="YAML" value="YAML"></el-option>
                  <el-option label="XML" value="XML" disabled></el-option>
                </el-select>
              </el-form-item>
            </el-col>
          </el-row>
        </el-form>
        <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="exportApi()" :loading="exportLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="exportApiDialogVisible = false;exportLoading = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
      </el-dialog>

        <!-- ========== version manager ========== -->
        <right-panel :show="versionDialog" @close="versionDialog = false">
            <el-button @click="addVersion">ADD</el-button>
            <el-table :data="versions" :border="false" style="width:100%">
                <el-table-column prop="version" label="version"></el-table-column>
                <el-table-column :label="$t('message.common.operation')" width="100">
                    <template slot-scope="scope">
                        <el-button type="text" icon="el-icon-delete" @click="delVersion(scope.row)" :title="$t('message.common.del')"></el-button>
                    </template>
                </el-table-column>
            </el-table>
        </right-panel>


    </section>
</template>
<script>
    import EnterpriseApi from './EnterpriseApi.js'

    export default EnterpriseApi
</script>
<style scoped>
    .left {
        float: left;
        width: 29%;
        height: calc(100vh - 96px);
        overflow: auto;
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
        padding: 10px;
    }
    .right {
        margin-left: 30%;
        height: calc(100vh - 96px);
        overflow-scrolling: auto;
        overflow: auto;
        position: relative;
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
        padding: 10px;
    }

    .custom-tree-node {
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: space-between;
        font-size: 14px;
        padding-right: 8px;
    }

</style>

