<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration">
        <div>
            <el-button icon="el-icon-plus" type="primary" @click="addGroup()">创建分组</el-button>
            <el-button icon="el-icon-refresh" type="success" @click="getGroup()">刷新</el-button>
        </div>

        <!--TODO v-for-->
        <div v-for="(item, i) in tableData"  >
            <div style="clear:both;"></div>
            <el-divider class="short-margin-divider"></el-divider>
            <div class="group-name" style="display: inline-block">
                <span style="line-height: 36px;font-size: 24px;color: #999;vertical-align:middle;" >{{item.name}}</span>
                <el-button class="edit-group" style="display: none;" @click="editGroup(item)">修改</el-button>
                <el-button class="edit-group" style="display: none;" @click="delGroup(item)">删除</el-button>
            </div>
            <div>
                <!--TODO v-for-->
                <div v-for="(jtem ,j) in item.enterpriseProjectList" class="groups-con" style="" @click="toProjectDetail()">
                    <div style="margin: 6px 0 0 6px;">
                        <span class="groups-con-title">
                            {{jtem.name}}
                        </span>
                    </div>
                    <div style="margin: 0 0 0 6px;">
                        <span class="groups-con-title2">
                            {{jtem.remark}}
                        </span>
                    </div>
                    <div style="background-color: rgba(0, 0, 0, 0.1);position: absolute;bottom: 0;width: 100%;text-align:center;line-height: 30px; ">
                        {{jtem.humanUpdateDate}}
                    </div>
                    <div class="groups-con-tools">
                        <a class="el-icon-edit" @click.stop="editData(jtem)"></a>
                        <a class="el-icon-delete" @click.stop="delData(jtem)"></a>
                    </div>
                </div>

                <div class="groups-con" style="background: url(/static/images/doc_image/plus.png) no-repeat center center;" @click="addData(item)"></div>
            </div>


        </div>


        <el-dialog :close-on-click-modal="false" :title="dialogTitle" :visible.sync="groupDialogVisible"
                   v-loading='dialogLoading' width="30%">
            <el-form label-width="50px" :model="groupSaveForm" ref="groupSaveForm" class="demo-form-inline" :rules="rules">
                <el-row>
                    <el-col :span="24">
                        <el-form-item label="name" prop="name">
                            <span slot="label">
                                <span>名称</span>
                            </span>
                            <el-input v-model="groupSaveForm.name" placeholder="分组名称" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="saveGroup()" :loading="dialogLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="groupDialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>

        <el-dialog :close-on-click-modal="false" :title="dialogTitle" :visible.sync="dialogVisible"  v-loading='dialogLoading'>
            <el-form label-width="100px" :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">


                <el-row>
                    <el-col :span="12">
                        <el-form-item label="name" prop="name">
                            <span slot="label">
                                <span>名称</span>
                                <el-tooltip class="item" effect="dark" content="项目名称" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                            <el-input v-model="saveForm.name" placeholder="项目名称" ></el-input>
                        </el-form-item>
                    </el-col>
                    <el-col :span="12">
                        <el-form-item label="visibility" prop="visibility">
                            <span slot="label">
                                <span>可见性</span>
                                <el-tooltip class="item" effect="dark" content="可见性：1公开，2私有(team_id)" placement="right">
                                    <i class="el-icon-question"></i>
                                </el-tooltip>
                            </span>
                            <el-select v-model="saveForm.visibility" style="width: 100%">
                                <el-option label="公开" value="1"></el-option>
                                <el-option label="私有" value="2"></el-option>
                            </el-select>
                        </el-form-item>
                    </el-col>

                </el-row>

                <el-row>
                    <el-col :span="24">
                        <el-form-item label="remark" prop="remark">
                            <span slot="label">
                                <span>备注</span>
                            </span>
                            <el-input type="textarea" :rows="1" v-model="saveForm.remark" placeholder="备注" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="saveData()" :loading="dialogLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="dialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>
    </section>
</template>
<script>
    import EnterpriseProjectPanel from './EnterpriseProjectPanel.js'

    export default EnterpriseProjectPanel
</script>
<style scoped>
    .group-name:hover .edit-group{
        display:inline-block !important;
    }
    .groups-con{
        position: relative;
        border: 1px solid #DDD;
        float: left;
        height: 120px;
        margin: 0 10px 28px 0;
        width: calc((100% - 50px) / 5);
        cursor:pointer;
    }
    .groups-con:hover{
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
    }
    .groups-con:hover .groups-con-tools{
        display: block;
    }
    .groups-con-title{
        font-size: 20px;
        color: #6D8095;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
        display: block;
    }
    .groups-con-title2{
        font-size: 16px;
        color: rgba(0, 0, 0, 0.3);
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
        display: block;
    }
    .groups-con .groups-con-tools{
        text-align: center;
        position: absolute;
        height: 26px;
        right: -1px;
        top: -26px;
        width: auto;
        background-color: #F2F2F2;
        padding: 2px;
        color: #999;
        border: 1px solid #DDD;
        display: none;
        border-radius: 5px 5px 0 0;
    }






</style>
<style>
    .short-margin-divider.el-divider--horizontal{
        margin: 12px 0;
    }
</style>

