<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration">

    </section>
</template>
<script>
    import EnterpriseProjectPanel from './EnterpriseProjectPanel.js'

    export default EnterpriseProjectPanel
</script>
<style scoped>

</style>

