<!-- Generated by DoPaaS for Codegen, refer: http://dts.dopaas.wl4g.com -->

<template>
    <section id="configuration" class="configuration">
        <el-form :inline="true" :model="searchParams" class="searchbar" @keyup.enter.native="onSubmit()">
            <el-form-item label="">
                <el-input v-model="searchParams.projectId" placeholder="" style="width:165px"></el-input>
            </el-form-item>
            <el-form-item label="">
                <el-input v-model="searchParams.version" placeholder="" style="width:165px"></el-input>
            </el-form-item>
            <input hidden />
            <el-form-item>
                <el-button @click="onSubmit" type="success" :loading="loading">{{$t('message.common.search')}}</el-button>
            </el-form-item>
            <el-button type="primary" style='float:right;margin-right:20px' @click="addData()" >+ </el-button>
        </el-form>

        <!--================================table================================-->
        <!-- 查询结果数值 -->
        <div class="query">
            <div class="query-left">
                <div class="line"></div>
                Result Total： <span class="number">{{total}}</span>
            </div>
        </div>
        <!-- 查询结果表格 -->
        <div>
            <template>
                <el-table :data="tableData" :border="false" style="width:100%">
                    <!--<el-table-column :label="$t('message.common.selectAll')" type="selection"></el-table-column>-->
                    <!--<el-table-column width="100" prop="id" label="ID"></el-table-column>-->
                    <el-table-column prop="projectId">
                        <template slot="header" slot-scope="scope">
                            <span></span>
                        </template>
                        <template slot-scope="{row}">
                            <span>{{row.projectId}}</span>
                        </template>
                    </el-table-column>
                    <el-table-column prop="version">
                        <template slot="header" slot-scope="scope">
                            <span></span>
                        </template>
                        <template slot-scope="{row}">
                            <span>{{row.version}}</span>
                        </template>
                    </el-table-column>
                    <el-table-column prop="updateDate">
                        <template slot="header" slot-scope="scope">
                            <span></span>
                        </template>
                        <template slot-scope="{row}">
                            <span>{{row.updateDate}}</span>
                        </template>
                    </el-table-column>
                    <el-table-column prop="updateBy">
                        <template slot="header" slot-scope="scope">
                            <span></span>
                        </template>
                        <template slot-scope="{row}">
                            <span>{{row.updateBy}}</span>
                        </template>
                    </el-table-column>
                    <el-table-column :label="$t('message.common.operation')" min-width="120">
                        <template slot-scope="scope">
                            <el-button type="text" icon="el-icon-edit" @click="editData(scope.row)" :title="$t('message.common.edit')"></el-button>
                            <el-button type="text" icon="el-icon-delete" @click="delData(scope.row)" :title="$t('message.common.del')"></el-button>
                        </template>
                    </el-table-column>
                </el-table>
            </template>
        </div>
        <el-pagination background layout="prev, pager, next" :total="total" @current-change='currentChange'></el-pagination>

        <!--================================save dialog================================-->
        <el-dialog :close-on-click-modal="false" :title="dialogTitle" :visible.sync="dialogVisible"  v-loading='dialogLoading'>
            <el-form label-width="150px" :model="saveForm" ref="saveForm" class="demo-form-inline" :rules="rules">
 
                <el-row>
                    <el-col :span="11">
                        <el-form-item label="projectId" prop="projectId">
                            <span slot="label">
                                <span></span>
                            </span>
                            <el-input v-model="saveForm.projectId" placeholder="" ></el-input>
                        </el-form-item>
                    </el-col>
                    <el-col :span="11">
                        <el-form-item label="version" prop="version">
                            <span slot="label">
                                <span></span>
                            </span>
                            <el-input v-model="saveForm.version" placeholder="" ></el-input>
                        </el-form-item>
                    </el-col>
                </el-row>
 
                <el-row>
                &nbsp;
                </el-row>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="saveData()" :loading="dialogLoading">{{$t('message.common.save')}}</el-button>
                <el-button @click="dialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>
    </section>
</template>
<script>
    import EnterpriseProjectVersion from './EnterpriseProjectVersion.js'

    export default EnterpriseProjectVersion
</script>
<style scoped>

</style>

