<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration" style="height: calc(100vh - 100px)">

        <fsviewer></fsviewer>




    </section>
</template>
<script>
    import EnterpriseTemplate from './EnterpriseTemplate.js'

    export default EnterpriseTemplate
</script>
<style scoped>

</style>

