<!-- Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com -->

<template>
    <section id="configuration" class="configuration" style="height: calc(100vh - 100px)">
        <editor
                :initialValue="editorText"
                height="100%"
                previewStyle="vertical"
                language="zh-CN"
                :plugins="[youtubePlugin]"
                :options="editorOptions"
        >
        </editor>
        <!--<div id="editor"></div>-->
    </section>
</template>
<script>
    import EnterpriseDocumentEdit from './EnterpriseDocumentEdit.js'

    export default EnterpriseDocumentEdit
</script>
<style scoped>

</style>

