// Generated by DevOps for Codegen, refer: http://dts.dopaas.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseProjectVersionList',
        method: 'enterpriseProjectVersionList',
        path: '/enterpriserepositoryversion/list',
        type: 'get',
        sysModule: global.udm
    },{
        name: 'getVersionsByRepositoryId',
        method: 'getVersionsByRepositoryId',
        path: '/enterpriserepositoryversion/getVersionsByRepositoryId',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseProjectVersion',
        method: 'saveEnterpriseProjectVersion',
        path: '/enterpriserepositoryversion/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseProjectVersionDetail',
        method: 'enterpriseProjectVersionDetail',
        path: '/enterpriserepositoryversion/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseProjectVersion',
        method: 'delEnterpriseProjectVersion',
        path: '/enterpriserepositoryversion/del',
        type: 'post',
        sysModule: global.udm
    },
]


