// Generated by DevOps for Codegen, refer: http://dts.dopaas.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseDocumentList',
        method: 'enterpriseDocumentList',
        path: '/enterprisedocument/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseDocument',
        method: 'saveEnterpriseDocument',
        path: '/enterprisedocument/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseDocumentDetail',
        method: 'enterpriseDocumentDetail',
        path: '/enterprisedocument/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseDocument',
        method: 'delEnterpriseDocument',
        path: '/enterprisedocument/del',
        type: 'post',
        sysModule: global.udm
    },

    {
        name: 'mdToHtml',
        method: 'mdToHtml',
        path: '/md/mdToHtml',
        type: 'post',
        sysModule: global.udm
    },

    {
        name: 'getTemplate',
        method: 'getTemplate',
        path: '/md/getTemplate',
        type: 'post',
        sysModule: global.udm
    },

    {
        name: 'formatTemplate',
        method: 'formatTemplate',
        path: '/md/formatTemplate',
        type: 'post',
        sysModule: global.udm
    },


]


