// Generated by DoPaaS for Codegen, refer: http://dts.dopaas.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseApiModuleList',
        method: 'enterpriseApiModuleList',
        path: '/enterpriseapimodule/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'getByVersionIdAndParentId',
        method: 'getByVersionIdAndParentId',
        path: '/enterpriseapimodule/getByVersionIdAndParentId',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseApiModule',
        method: 'saveEnterpriseApiModule',
        path: '/enterpriseapimodule/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseApiModuleDetail',
        method: 'enterpriseApiModuleDetail',
        path: '/enterpriseapimodule/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseApiModule',
        method: 'delEnterpriseApiModule',
        path: '/enterpriseapimodule/del',
        type: 'post',
        sysModule: global.udm
    },
]


