// Generated by DoPaaS for Codegen, refer: http://dts.dopaas.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseProjectList',
        method: 'enterpriseProjectList',
        path: '/enterpriserepository/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseProject',
        method: 'saveEnterpriseProject',
        path: '/enterpriserepository/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseProjectDetail',
        method: 'enterpriseProjectDetail',
        path: '/enterpriserepository/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseProject',
        method: 'delEnterpriseProject',
        path: '/enterpriserepository/del',
        type: 'post',
        sysModule: global.udm
    },
]


