// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseTeamList',
        method: 'enterpriseTeamList',
        path: '/enterpriseteam/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseTeam',
        method: 'saveEnterpriseTeam',
        path: '/enterpriseteam/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseTeamDetail',
        method: 'enterpriseTeamDetail',
        path: '/enterpriseteam/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseTeam',
        method: 'delEnterpriseTeam',
        path: '/enterpriseteam/del',
        type: 'post',
        sysModule: global.udm
    },
]


