// Generated by DevOps for Codegen, refer: http://dts.dopaas.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseApiList',
        method: 'enterpriseApiList',
        path: '/enterpriseapi/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'getApisByVersionid',
        method: 'getApisByVersionid',
        path: '/enterpriseapi/getApisByVersionid',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'getByModuleId',
        method: 'getByModuleId',
        path: '/enterpriseapi/getByModuleId',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseApi',
        method: 'saveEnterpriseApi',
        path: '/enterpriseapi/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseApiDetail',
        method: 'enterpriseApiDetail',
        path: '/enterpriseapi/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseApi',
        method: 'delEnterpriseApi',
        path: '/enterpriseapi/del',
        type: 'post',
        sysModule: global.udm
    },
    {
        name: 'importApi',
        method: 'importApi',
        path: '/enterpriseapi/importApi',
        type: 'post',
        sysModule: global.udm
    },
    {
        name: 'getConverterProviderKind',
        method: 'getConverterProviderKind',
        path: '/enterpriseapi/getConverterProviderKind',
        type: 'get',
        sysModule: global.udm
    },
]


