// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

import global from "../../common/global_variable";

export default [
    {
        name: 'enterpriseGroupList',
        method: 'enterpriseGroupList',
        path: '/enterpriserepositorygroup/list',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'saveEnterpriseGroup',
        method: 'saveEnterpriseGroup',
        path: '/enterpriserepositorygroup/save',
        type: 'post',
        dataType: 'json',
        sysModule: global.udm
    },
    {
        name: 'enterpriseGroupDetail',
        method: 'enterpriseGroupDetail',
        path: '/enterpriserepositorygroup/detail',
        type: 'get',
        sysModule: global.udm
    },
    {
        name: 'delEnterpriseGroup',
        method: 'delEnterpriseGroup',
        path: '/enterpriserepositorygroup/del',
        type: 'post',
        sysModule: global.udm
    },
]


