<!-- Generated by DoPaaS for Codegen, refer: http://dts.dopaas.wl4g.com -->

<template>
    <section id="configuration" class="templateEdit" style="height: calc(100vh - 100px)">

        <el-row style="height: 100%" :gutter="10">

            <el-col :span="6" style="height: 100%">
                <div class="card" style="height: 100%; overflow: auto;">
                    <fsviewer :sub-path="'/md'" @openFile="openFile" :getClusterContextmenus="getClusterContextmenus"></fsviewer>
                </div>
            </el-col>

            <el-col :span="18" style="height: 100%">
                <el-row style="margin-bottom: 10px;box-shadow: 0 0 8px rgba(0, 0, 0, 0.4) ">
                    <el-col :span="18" style="min-height: 1px">
                        <el-breadcrumb separator-class="el-icon-arrow-right" style="font-size: 28px !important;line-height: 28px !important;">
                            <el-breadcrumb-item v-for="item in path.split('/')" v-if="item && item != ''">
                                {{item}}
                            </el-breadcrumb-item>
                        </el-breadcrumb>
                    </el-col>
                    <el-col :span="4" style="min-height: 1px">
                        <span style="line-height: 28px">
                            {{data.updateTime}}
                        </span>
                    </el-col>
                    <el-col :span="2">
                        <el-button style="float: right"  type="primary" @click="saveFile">保存</el-button>
                    </el-col>
                </el-row>

                <el-row style="height: calc(100% - 38px);box-shadow: 0 0 8px rgba(0, 0, 0, 0.4)">
                    <el-col :span="12" style="height: 100%">
                        <div style="height: 100%; width: 100%;">
                            <!--<textarea ref="mycode" class="codesql" v-model="code" style="height: 100%;width: 100%"></textarea>-->

                            <editor
                                    ref="myToastEditor"
                                    :initialValue="editorText"
                                    height="100%"
                                    previewStyle="none"
                                    language="zh-CN"
                                    :options="editorOptions"
                                    @change="onEditorChange"
                            >
                            </editor>
                        </div>
                    </el-col>

                    <el-col :span="12" style="height: 100%">
                        <div id="myMdView" class="markdown-body" style="height: 100%; width: 100%;overflow: auto">
                            <!--<textarea ref="mycode" class="codesql" v-model="code" style="height: 100%;width: 100%"></textarea>-->

                        </div>
                    </el-col>
                </el-row>

            </el-col>
        </el-row>



        <el-dialog title="API" :visible.sync="apiDialogVisible" width="50%" >
            <el-row>
                <el-col :span="12">
                    <el-select v-model="project" placeholder="请选择项目" style="width: 100%" @change="getVersionsByRepositoryId">
                        <el-option
                                v-for="item in projects"
                                :key="item.id"
                                :label="item.name"
                                :value="item.id">
                        </el-option>
                    </el-select>
                </el-col>
                <el-col :span="12">
                    <el-select v-model="versionId" placeholder="请选择版本" style="width: 100%" @change="reloadApiTree">
                        <el-option
                                v-for="item in versions"
                                :key="item.id"
                                :label="item.version"
                                :value="item.id">
                        </el-option>
                    </el-select>
                </el-col>
            </el-row>
            <el-row>
                <el-col :span="24">
                    <div style="max-height: 300px;overflow: auto">

                        <el-tree ref="apiTree" node-key="key" :props="defaultProps" :load="loadModule" lazy @node-click="handleNodeClick">
                            <span class="custom-tree-node" slot-scope="{ data, node  }">
                                <span>{{ node.label }}</span>
                                <span>
                                  <el-button v-if="!isApi(data)" type="text" size="mini" class="el-icon-refresh" @click="() => refreshByNode(node)"></el-button>
                                </span>
                            </span>
                        </el-tree>


                    </div>
                </el-col>
            </el-row>
            <el-row style="border: 1px solid #DCDFE6;">
                <el-col :span="8">
                    <div >
                        <span v-if="apiId && apiId != ''" style="font-size: 16px;color: #8c8c8c">
                            {#api_info_{{apiId}}}
                        </span>
                    </div>
                </el-col>
            </el-row>



            <span slot="footer" class="dialog-footer">
                <el-button :disabled="!apiId || apiId == ''" type="primary" @click="insertApi()">插入</el-button>
                <el-button @click="apiDialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>


        <el-dialog title="API" :visible.sync="beforeFormatDialogVisible" width="50%" >
            <el-row>
                <el-col :span="24">
                    <el-select v-model="selectedTemplate" placeholder="请选择模版" style="width: 100%">
                        <el-option
                                v-for="item in templates"
                                :key="item"
                                :label="item"
                                :value="item">
                        </el-option>
                    </el-select>
                </el-col>
            </el-row>

            <span slot="footer" class="dialog-footer">
                <el-button :disabled="!selectedTemplate || selectedTemplate == ''" type="primary" @click="formatTotal">发布</el-button>
                <el-button @click="beforeFormatDialogVisible = false;">{{$t('message.common.cancel')}}</el-button>
            </span>
        </el-dialog>



    </section>
</template>
<script>
    import EnterpriseMd from './EnterpriseMd.js'

    export default EnterpriseMd
</script>

<style scoped>
    .left {
        float: left;
        width: 300px;
        height: 100%;
    }
    .right {
        margin-left: 310px;
        height: 100%;
        overflow-scrolling: auto;
        position: relative;

    }
    .top-card{
        box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
    }

    .card{
        box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.4);
    }



</style>

<style>

</style>

